#!/bin/sh

sudo pacman -S --noconfirm --needed networkmanager polkit zoxid zoxide htop neovim tmux lf lsd man-db inetutils whois wget netcat python3 uv python3-requests python3-pygame npm nodejs go pipewire pipewire-pulse pipewire-alsa pipewire-pulse pipewire-jack wireplumber pulsemixer xorg-server xorg-apps xorg-xinit xf86-input-libinput xf86-video-intel xorg-xrandr xorg-xset xdotool hsetroot feh i3-wm dunst polybar rofi ttf-ubuntu-mono-nerd noto-fonts-emoji noto-fonts-cjk flameshot mpv thunar papirus-icon-theme arc-theme lxappearance lxqt-policykit libnotify

# Install yay if it has not already been installed
CUR_DIR=$(pwd)

if ! command -v yay >/dev/null 2>&1; then
    sudo pacman -Sy --needed --noconfirm base-devel git
    git clone https://aur.archlinux.org/yay.git "$HOME/_temp"
    cd "$HOME/_temp" || exit 1
    makepkg -si --noconfirm
    cd "$CUR_DIR" || exit 1
    rm -rf "$HOME/_temp"
else

fi

# Install AUR packages
yay -S --noconfirm --needed librewolf-bin rofimoji 

# Install zsh fast syntax highlighting plugin
mkdir -p ~/.local/share/zsh/fast-syntax-highlighting
git clone --depth=1 https://github.com/zdharma-continuum/fast-syntax-highlighting ~/.local/share/zsh/fast-syntax-highlighting

# Setup zsh cache directory
mkdir -p .cache/zsh

# Enable global services
sudo systemctl enable --now NetworkManager
sudo systemctl start --now NetworkManager

# Enable user services
systemctl --user enable --now pipewire pipewire-pulse wireplumber
systemctl --user start --now pipewire pipewire-pulse wireplumber

# Setup symlinks
ln -sf /usr/bin/zsh /usr/bin/sh
ln -sf /usr/bin/vi  /usr/bin/nvim
ln -sf /usr/bin/vim /usr/bin/nvim
